
defaults:
  - scope:
      path: "sitemap.xml"
    values:
      layout: nullxw


plugins:
- jekyll-sitemap

exclude:
- django
- wordpress
- vendor/
- vendor/bundle/
- node_modules/
- Gemfile
- Gemfile.lock
